### ISSUE TITLE
MaskRCNN not using gpu

### ISSUE THREAD

**Issue by davidb1** [matterport/Mask_RCNN#1360]
When doing inference I see a CPU spike to 100% but no change for the GPU usage. How can I make sure MaskRCNN uses my GPU instead of CPU?

**Comment by davidb1** [comment]
Had to install a newer version of tensorflow-gpu than the one that comes with maskrcnn

**Comment by ridwaniyas** [comment]
Use Google Colab https://colab.research.google.com/

**Comment by freezurbern** [comment]
You may also see high CPU usage if you are scaling the training data with IMAGE_RESIZE_MODE, IMAGE_MIN_DIM, IMAGE_MAX_DIM. This was a bottleneck for my model that prevented the GPU from running at high utilization.

**Comment by qchenclaire** [comment]
> When doing inference I see a CPU spike to 100% but no change for the GPU usage. How can I make sure MaskRCNN uses my GPU instead of CPU?

Me too. I

> Had to install a newer version of tensorflow-gpu than the one that comes with maskrcnn

I'm using tf 1.10 and keras 2.2.4, but still cannot use gpus

**Comment by h-ann** [comment]
I had the same problem with, MaskRCNN didn't use gpu.
The problem was fixed after removing tensorflow-gpu and installing tf-nightly-gpu.

My current versions are:
Name: tensorflow       Version: 1.13.1
Name: tf-nightly-gpu   Version: 1.14.1.dev20190419

**Comment by davidb1** [comment]
> > When doing inference I see a CPU spike to 100% but no change for the GPU usage. How can I make sure MaskRCNN uses my GPU instead of CPU?
> 
> Me too. I
> 
> > Had to install a newer version of tensorflow-gpu than the one that comes with maskrcnn
> 
> I'm using tf 1.10 and keras 2.2.4, but still cannot use gpus

@qchenclaire Did you install tensorflow-gpu or just tensorflow? And did you set the session to use gpu?

**Comment by chAwater** [comment]
I had the same problem, and I fixed it by **reinstall** tensorflow-gpu.

You also can create a new conda env (Keras=2.1.3 is for #958 ).
`conda create -n <ENV> python=3.x keras=2.1.3 tensorflow-gpu`

After that, you can first test tensorflow-gpu is working by:
```python
import tensorflow as tf
print (tf.test.gpu_device_name())
# or
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
```

If tensorflow-gpu is working, then you can try `demo.ipynb`, hopefully it will work too.

---

@qchenclaire Could you please give more info. if you still have this problem.

@davidb1 Please close the issue, if you solve it already.

**Comment by Vanouche** [comment]
I had the same problem with the absence of the cudart64_101.dll file. All I had to do was install the correct version of CUDA and Cudnn. 
The versions i use:
tensorflow 2.2.0
CUDA 10.1
Cudnn 7.6.0
