### ISSUE TITLE
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by ZhonghuaTian** [matterport/Mask_RCNN#1620]
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
@

**Comment by amsr9** [comment]
I'm having the same issue as I'm using Google Colab! It used to work two months ago. Any ideas?

**Comment by Prasandeep-Singh** [comment]
I was also getting the same error, but I am using GPU.
I included this "TF_FORCE_GPU_ALLOW_GROWTH=true" before command, like use this:
"TF_FORCE_GPU_ALLOW_GROWTH=true python3 samples/drone/drone.py train --dataset=path/to/drone/Dataset --weights=coco"

it worked for me!

**Comment by amsr9** [comment]
Do you mean adding this argument within the command line? I’m importing the library and using it on Google Colab not sure how to add it there!

**Comment by Prasandeep-Singh** [comment]
yes, I used it in the command line.

**Comment by gerkulesov** [comment]
If someone want to use this workaround in Jupyter Notebook, you can add TF_FORCE_GPU_ALLOW_GROWTH=true before command for running notebook:
`TF_FORCE_GPU_ALLOW_GROWTH=true jupyter notebook`

**Comment by pythongo1** [comment]
Thanks a lot. 
I have the same problem in jupyter notebook, and I solve this by using 
`TF_FORCE_GPU_ALLOW_GROWTH=true jupyter notebook`
