### ISSUE TITLE
There is a problem running on the GPU,I hope it can be answered

### ISSUE THREAD

**Issue by breazyG** [matterport/Mask_RCNN#2395]
problem：
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[400,256,28,28] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node mrcnn_mask_deconv/conv2d_transpose (defined at \anaconda1\envs\tensorflow2\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_keras_scratch_graph_19043]

Function call stack:
keras_scratch_graph

I think it's the GPU running memory problem，but I don't know how to reduce the parameters in the config or other parameters to run，I hope it can be answered

**Comment by jtk1919** [comment]
I think you are running a batch of 400 images in one go, and you are running out of GPU memory.

Try, in config
IMAGES_PER_GPU = 1

Then increase this like 2, 4, 6, 8...  until you find the maximum batch size the GPU memory can handle.

**Comment by breazyG** [comment]
I used your method and changed the size of batch value on this basis. Now it can run successful
Thank you so much

**Comment by breazyG** [comment]
@jtk19

**Comment by sahaj432** [comment]
Close #2395

**Comment by sahaj432** [comment]
Fixes #2395

**Comment by jiaweifan** [comment]
What type of GPU are you using?Thank you!

**Comment by breazyG** [comment]
@jiaweifan  my GPU is 1650 ，problem is solved

**Comment by jiaweifan** [comment]
> @jiaweifan my GPU is 1650 ，problem is solved



The video memory of GTX1650 is 4GB, and the video memory of 1050ti I used is also 4GB, but after setting IMAGES_PER_GPU=1, ResourceExhaustedError will still appear in the second stage of training. Why is this?

**Comment by breazyG** [comment]
You can try to reduce your batchsize and change the backbone，I think them are more important
I also changed many parameters in config to run，I also just started contacting this, hope to help you

**Comment by jiaweifan** [comment]
> You can try to reduce your batchsize and change the backbone，I think them are more important
> I also changed many parameters in config to run，I also just started contacting this, hope to help you

May I know which parameters you have modified in config?Thank you very much!

**Comment by raditharch** [comment]
Hello, could you please tell me how did you install tensorflow with the gpu? I'm using !pip install tensorflow_gpu==1.9.0, but got an error. Thanks.
![image](https://user-images.githubusercontent.com/72731175/97661016-ca3f3c80-1aa5-11eb-88d9-2303f447c6a6.png)

**Comment by TimNagle-McNaughton** [comment]
If you still care, you need to do "install tensorflow-gpu==1.9.0"--note the hyphen not underscore.
