### ISSUE TITLE
How much RAM on GPU does this require?

### ISSUE THREAD

**Issue by michalstepniewski** [matterport/Mask_RCNN#248]
Ran it on GPU with 12GB RAM and got OutOfMemory Error.
Now will try on 16GB RAM GPU. How much RAM on GPU does this library require?
(eg. train_shapes.ipynb)

**Comment by Xyza1972** [comment]
I think it depends  on your batch size and training image size.

I can train all layers in 6G memory GPU but only train one image of 512x512

**Comment by fastlater** [comment]
@Xyza1972 how much ran on GPU for demo.ipynb? I tried on 2GB RAM GPU and I get cudnn_status_mapping_error. This error supposed to be related to PATH but after follow several instructions from different webpages, I found one thread where they mention that this error could be related to memory. Screen goes BLANK and them kill the process.

**Comment by Xyza1972** [comment]
@fastlater I never saw mapping_error before.

Now I am running modified train_shape.ipynb with my own dataset on single GPU with 12G memory.
I train 5 images of 512*512. I also tried to train on 2 GPUs but there was broken pipe error so I gave up.

**Comment by fastlater** [comment]
@Xyza1972  Thank you for your reply.
I will update my gpu soon (I will get a GTX 1080 Ti) but what was the pipe error about? I keep getting cudnn_status_mapping_error. Did you get something similar?

**Comment by Xyza1972** [comment]
@fastlater I suggest you to run train_shape.ipynb first because it generates dataset before training and does not require coco dataset. For my last 8 months with deep learning, I have never seen sudnn_status_mapping_error. According to my  [quick search](https://github.com/tensorflow/tensorflow/issues/2190), it happens in tf0.x and older version of ubuntu. 

Have you check versions?

I use tf1.4 and cuda8.0 in GTX Titan, ubuntu 16.4, and it works fine.  I created extra kernel for tensorflow.

**Comment by fastlater** [comment]
Well, I will try with cuda8.0. I have been trying with tf.1.5, cuda 9.0 and keep crashing.
