### ISSUE TITLE
 failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED while training during Epoch 1/1

### ISSUE THREAD

**Issue by DylanWake** [matterport/Mask_RCNN#2510]
## Error Logs
```
Epoch 1/1
C:\Users\DanielSun\PycharmProjects\FRC-opencv-python\venv\lib\site-packages\skimage\transform\_warps.py:830: FutureWarning: Input image dtype is bool. Interpolation is not defined with bool data type. Please set order to 0 or explicitely cast input image to another data type. Starting from version 0.19 a ValueError will be raised instead of this warning.
  order = _validate_interpolation_order(image.dtype, order)
2021-03-16 08:02:53.951349: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-03-16 08:02:54.762683: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-03-16 08:11:53.875933: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
2021-03-16 08:11:55.140273: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
2021-03-16 08:11:55.145031: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_grad_input_ops.cc:1161 : Not found: No algorithm worked!
2021-03-16 08:11:55.145264: I tensorflow/stream_executor/stream.cc:4976] [stream=0000021CEEED89D0,impl=0000021CE3F81AF0] did not memset GPU location; source: 000000F3A407C788; size: 8388608; pattern: ffffffff
2021-03-16 08:11:55.145581: I tensorflow/stream_executor/stream.cc:4976] [stream=0000021CEEED89D0,impl=0000021CE3F81AF0] did not memset GPU location; source: 000000F3A407C7A8; size: 8388608; pattern: ffffffff
2021-03-16 08:11:55.145736: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_grad_input_ops.cc:1161 : Not found: No algorithm worked!
2021-03-16 08:11:55.145844: I tensorflow/stream_executor/stream.cc:4963] [stream=0000021CEEED89D0,impl=0000021CE3F81AF0] did not memzero GPU location; source: 000000F3A407E558
2021-03-16 08:11:55.145868: I tensorflow/stream_executor/stream.cc:4963] [stream=0000021CEEED89D0,impl=0000021CE3F81AF0] did not memzero GPU location; source: 000000F3A3E8E308
2021-03-16 08:11:55.146095: I tensorflow/stream_executor/stream.cc:316] did not allocate timer: 000000F3A3E8E2B0
2021-03-16 08:11:55.146201: I tensorflow/stream_executor/stream.cc:1964] [stream=0000021CEEED89D0,impl=0000021CE3F81AF0] did not enqueue 'start timer': 000000F3A3E8E2B0
2021-03-16 08:11:55.145955: I tensorflow/stream_executor/stream.cc:316] did not allocate timer: 000000F3A407E500
2021-03-16 08:11:55.146346: I tensorflow/stream_executor/stream.cc:1976] [stream=0000021CEEED89D0,impl=0000021CE3F81AF0] did not enqueue 'stop timer': 000000F3A3E8E2B0
2021-03-16 08:11:55.146524: F tensorflow/stream_executor/gpu/gpu_timer.cc:65] Check failed: start_event_ != nullptr && stop_event_ != nullptr 
2021-03-16 08:11:55.146423: I t
Process finished with exit code -1073740791 (0xC0000409)
```

dedicated GPU memory occupation on exception: 4.1 GB / 8 GB

## Tensorflow Configuration 
```python
cfg = tf.ConfigProto()
cfg.gpu_options.allow_growth=True
cfg.gpu_options.per_process_gpu_memory_fraction = 0.90
sess = tf.Session(config=cfg)
```

## Code Section of Exception:
```python
model.train(dataset_train, dataset_val,
            learning_rate=config.LEARNING_RATE,
            epochs=1,
            layers='all')
```
modified model of the example `train_shapes.ipynb`
network : `resnet 101`

## Hardware Details: 

CPU: i7-10750H  ( 6 Cores )
GPU: RTX 3070 Laptop GPU 1299MHZ
CUDA version : 10.0
CUDnn version : 7.6.5
Operating System : Windows 10
Environmental Variables:
```
CUDA_CACHE_MAXSIZE = 2147483648
CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
```

## Library Details (Python3.7):
```
absl-py              0.12.0
astor                0.8.1
backcall             0.2.0
cached-property      1.5.2
colorama             0.4.4
cycler               0.10.0
Cython               0.29.22
decorator            4.4.2
gast                 0.2.2
google-pasta         0.2.0
grpcio               1.36.1
h5py                 2.10.0
imageio              2.9.0
imgaug               0.4.0
importlib-metadata   3.7.3
ipython              7.21.0
ipython-genutils     0.2.0
jedi                 0.18.0
Keras                2.2.5
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
kiwisolver           1.3.1
Markdown             3.3.4
matplotlib           3.3.4
networkx             2.5
numpy                1.20.1
opencv-python        4.5.1.48
opt-einsum           3.3.0
parso                0.8.1
pickleshare          0.7.5
Pillow               8.1.2
pip                  21.0.1
prompt-toolkit       3.0.17
protobuf             3.15.6
Pygments             2.8.1
pyparsing            2.4.7
python-dateutil      2.8.1
PyWavelets           1.1.1
PyYAML               5.4.1
scikit-image         0.18.1
scipy                1.6.1
setuptools           54.1.2
Shapely              1.7.1
six                  1.15.0
tensorboard          1.15.0
tensorflow-estimator 1.15.1
tensorflow-gpu       1.15.0
termcolor            1.1.0
tifffile             2021.3.5
traitlets            5.0.5
typing-extensions    3.7.4.3
wcwidth              0.2.5
Werkzeug             1.0.1
wheel                0.36.2
wrapt                1.12.1
zipp                 3.4.1
```

**Comment by DylanWake** [comment]
Solution:

Add this piece of code before the training starts:
```python
config = tf.compat.v1.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.9
config.gpu_options.allow_growth = True
config.gpu_options.polling_inactive_delay_msecs = 10
session = tf.compat.v1.Session(config=config)
```

**Comment by lkrboom** [comment]
hello, I meet the same question,but your solution can't work.could you tell me the reason why this question happen? thanks a lot

**Comment by DylanWake** [comment]
OK so the issue was caused by a compatibility problem between the tensorflow 1.x and 30 Series GPU drivers
The solution to this was to install an linux system on your computer (Ubuntu 20.04 LTS I used)
Then install a third-party build of tensorflow 1.x that supports RTX 30 Series GPUs
// I used tf-nightly 1.15 to run this model
there are some configurations with things like keras but you can adjust them as the reqirements in the original mrcnn project

**Comment by lkrboom** [comment]
I can get the way from you to understand the question.
my hardware details:
GPU: RTX 3080
CUDA version : 10.0
CUDnn version : 7.6.5
Operating System : ubuntu 18.04
software details:
tensorflow-gpu 1.15
I meet the same question when I run the model(not mrcnn),and add your solution code before the training starts.But the question still exists.
I test the available of  gpu when import tensorflow.
But the above question raise when the code run.

**Comment by DylanWake** [comment]
um, so that should be a memory overflow, try to reduce your batch size might be helpful
My solution code was to allow tf to dynamically allocate memory (allow growth), and the portion was basically the amount of cuda memory that tf is allowed to use.

**Comment by prantik-pdeb** [comment]
GPU: RTX 3080
CUDA version: 10.0
CUDnn version: 7.6
Operating System: ubuntu 16.04
software details:
TensorFlow-GPU 1.14
How do I resolve the same issue???

**Comment by linju2022perfect** [comment]
> GPU: RTX 3080 CUDA version: 10.0 CUDnn version: 7.6 Operating System: ubuntu 16.04 software details: TensorFlow-GPU 1.14 How do I resolve the same issue???

Hello, have you resolved this issue? I encountered the same problem, but unfortunately, our configuration is basically the same

**Comment by RuYingran** [comment]
GPU：RTX 3060
CUDA 版本：10.0
CUDnn 版本：7.4
操作系统：win 11
软件详情：
TensorFlow-GPU 1.15.0
报错：E tensorflowream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED请问怎么解决

**Comment by anvvvv** [comment]
hello,I want to know where is the train starts
