### ISSUE TITLE
AttributeError in loading training dataset

### ISSUE THREAD

**Issue by ErinYang96** [matterport/Mask_RCNN#2829]
Hello,

When using [Mask-RCNN-TF2.7.0-keras2.8.0](https://github.com/Kamlesh364/Mask-RCNN-TF2.7.0-keras2.8.0)
 for my test, I have some problems in just loading my training and validation dataset.

I provide my code here so you can better figure out what's wrong.

# Basic setup
> 
    import os
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # Avoid AVX Warning from using CPU
    import sys
    import random
    import math
    import re
    import time
    import numpy as np
    import cv2
    import matplotlib
    import matplotlib.pyplot as plt
    import h5py
    from imgaug import augmenters as iaa
    from imgaug import parameters as iap
    from glob import glob

    # Root directory of the project
    ROOT_DIR = os.path.abspath('/Mask_RCNN2.0/')
    
    # Import Mask RCNN
    sys.path.append(ROOT_DIR)  # To find local version of the library
    from mrcnn.config import Config
    from mrcnn import utils
    import mrcnn.model as modellib
    from mrcnn import visualize
    from mrcnn.model import log
    
    # Directory to save logs and trained model
    MODEL_DIR = os.path.join(ROOT_DIR, "logs")

    # Local path to trained weights file
    COCO_MODEL_PATH = os.path.join(ROOT_DIR, "mask_rcnn_coco.h5")
    # Download COCO trained weights from Releases if needed
    if not os.path.exists(COCO_MODEL_PATH):
        utils.download_trained_weights(COCO_MODEL_PATH)

    import tensorflow as tf
    config = tf.compat.v1.ConfigProto()
    gpus = tf.config.experimental.list_physical_devices('GPU') # If there is any GPU available
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True) # Allocating GPU memory
    # config.gpu_options.allow_growth=True
    config.gpu_options.per_process_gpu_memory_fraction = 0.6 # Maximum consumption of GPU limit to 0.6  
    sess = tf.compat.v1.Session(config=config)

    # for visualization
    def get_ax(rows=1, cols=1, size=8):
        """Return a Matplotlib Axes array to be used in
        all visualizations in the notebook. Provide a
        central point to control graph sizes.
    Change the default size attribute to control the size
    of rendered images
    """
    _, ax = plt.subplots(rows, cols, figsize=(size*cols, size*rows))
    return ax
    classes = {1: 'trout'}
    class Config(Config):
    NAME = 'trout'
# Configuration
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1
    # BATCH_SIZE = IMAGES_PER_GPU * GPU_COUNT
    
    NUM_CLASSES = len(classes) + 1  # background + number of classes

    IMAGE_MIN_DIM = 128
    IMAGE_MAX_DIM = 128
    
    IMAGE_RESIZE_MODE = 'square'

    # Use smaller anchors because our image and objects are small
    RPN_ANCHOR_SCALES = (8, 16, 32, 64, 128) # Refer to the setup in train_shapes.ipynb

    # Reduce training ROIs per image because the images are small and have
    # few objects. Aim to allow ROI sampling to pick 33% positive ROIs.
    TRAIN_ROIS_PER_IMAGE = 32

    # Use a small epoch since the data is simple
    STEPS_PER_EPOCH = 100

    # use small validation steps since the epoch is small
    VALIDATION_STEPS = 5
    
    config = Config()
    config.display()
# Dataset
    from multiprocessing import Lock, Value, Pool, cpu_count
    import tqdm

    def load_images(i, images, annotation_file, temp):
        path = os.path.join(images[i], 'image')
        img_path = os.path.join(temp, os.path.split(path)[0].replace('/', '-').replace(':', '') + '.png')
        if os.path.exists(img_path):
            height, width = cv2.imread(img_path).shape[:2]
        else:
            with h5py.File(annotation_file, 'r') as h5_file:
                height, width = h5_file[path][:].shape[:2]
                image = h5_file[path][:]
                cv2.imwrite(img_path, image[:, :, ::-1])        
        lock.acquire()
        count.value += 1
        print('Reading images: {:.2f} %'.format(100 * count.value / len(images)),
              sep=' ', end='\r' if count.value < len(images) else '\n', flush=True)
        lock.release()
        return (i, path, width, height)

    def init_pool(l, c):
        global lock, count
        lock = l
        count = c

    class Dataset(utils.Dataset):
        
        def load_images(self, annotation_file, classes, source, mode='full'):
            self.classes = classes
            self.annotation_file = annotation_file
            self.temp = os.path.join(os.path.join(os.path.dirname(annotation_file), os.path.split(annotation_file)[-1] + 'temp'))
            if not os.path.exists(self.temp):
                os.mkdir(self.temp)
            with h5py.File(self.annotation_file, 'r') as h5_file:
                for c in self.classes:
                    self.add_class(source, c, self.classes[c])
                self.images = h5_file['annotations'][:].astype(np.str)
            np.random.seed(0)
            image_idx = np.arange(self.images.size)
            val_idx = np.random.choice(image_idx, image_idx.size // 6)
            if mode == 'train':
                self.images = self.images[np.invert(np.isin(image_idx, val_idx))]
            elif mode == 'val':
                self.images = self.images[np.isin(image_idx, val_idx)]
            else:
                print('Warning: set mode to "train" or "val", otherwise using full dataset')
                
            l = Lock()
            c = Value('d', 0)
            if __name__ == "__main__":
                with Pool(processes=cpu_count(), initializer=init_pool, initargs=(l, c)) as pool:
                    to_add = pool.starmap(load_images, list(zip(np.arange(len(self.images)),
                                                                [self.images] * len(self.images),
                                                                [self.annotation_file] * len(self.images),
                                                                [self.temp] * len(self.images))))
                    for (i, path, width, height) in to_add:
                        self.add_image(source, image_id=i, path=path, width=width, height=height)
                        
                    pool.close()
                    pool.join()       
        
        def load_image(self, image_id):
            info = self.image_info[image_id]
            path = info['path']
            img_path = os.path.join(self.temp, os.path.split(path)[0].replace('/', '-').replace(':', '') + '.png')
            print(img_path)
            image = cv2.imread(img_path)[:, :, ::-1]
            return image
        
        def load_mask(self, image_id):
            info = self.image_info[image_id]
            img_path = info['path']
            path = os.path.split(img_path)[0]
            with h5py.File(self.annotation_file, 'r') as h5_file:
                mask = h5_file[os.path.join(path, 'mask')][:]
                classes = h5_file[os.path.join(path, 'class_names')][:].astype(np.str)
            use = np.array([idx for idx, name in enumerate(classes) for c in self.classes if name in self.classes[c].split(',')], dtype=np.int32)
            class_ids = np.array([c for name in classes for c in self.classes if name in self.classes[c].split(',')], dtype=np.int32)
            mask = mask[:, :, use]
            non_empty = mask.sum(axis=(0, 1)) > 10
            return mask[:, :, non_empty], class_ids[non_empty]
        
        def prepare(self):
            super().prepare()
            print('{} images, classes: '.format(len(self.image_ids)), *['[{}: {}]'.format(idx, self.classes[idx]) for idx in self.classes])

    augmentation = iaa.Sequential([   
        
        iaa.Fliplr(0.5),
        iaa.Flipud(0.5),
        iaa.Affine(rotate=iap.Choice([0,90,180,270])),
        iaa.Affine(scale={'x': (0.8, 1.2), 'y': (0.8, 1.2)},
                          translate_percent={'x': (-0.2, 0.2), 'y': (-0.2, 0.2)},
                          rotate=(-45, 45))
        ], random_order=True)
# Load Dataset (where the problem occurs)
```
dataset_train = Dataset()
dataset_train.load_images(annotation_file='/Mask_RCNN2.0/trout/Dataset/314_0_out.h5',
      classes=classes, source='trout', mode = 'train')
dataset_train.prepare()
```

The error info is as follow, and it seems to be circulating and can't stop even if I stop the kernel.

> ![image](https://user-images.githubusercontent.com/100861190/168794689-5f602672-3e68-4b6e-b0c2-cf77eb44fe4e.png)

**My computer setup:**
GPU: NVIDIA Quadro P620, 2GB
CUDA: 11.2
cuDNN: 8.1
tensorflow 2.8.0
Keras 2.7.0
windows 10

It only takes a few second when I run my code on Google Colab (Ubuntun 18.04, run perfectly), but it takes a long time on local machine with the error message `AttributeError: module 'tensorflow.compat.v2.__internal__.distribute' has no attribute  'strategy_supports_no_merge_call`, and both CPU and GPU are almost out of memory. 

I wonder if there is something different between Ubuntun/Linux system and windows 10 that I haven't notice? I have previously tested tensorflow 1.x on windows 10, and similar problem occurs. This really troubles me for a long time. Could anyone please help me?

Thanks in advance for your kindness.

Best,
Erin

**Comment by ErinYang96** [comment]
Hi, I have solved the problem follow [this link](https://github.com/tensorflow/tensorflow/issues/53510). It is caused by version mismatch in my case. I will close the issue now.
