### ISSUE TITLE
OOM when allocating tensor

### ISSUE THREAD

**Issue by mldm4** [matterport/Mask_RCNN#44]
First of all I would like to thank the authors for such a great work.
When running the` train_shapes` notebook, I get the following error message 3 times in the first epoch. 

```
ResourceExhaustedError: OOM when allocating tensor with shape[256,256,28,28]
	 [[Node: mrcnn_mask_deconv/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](mrcnn_mask_deconv/stack, mrcnn_mask_deconv/kernel/read, mrcnn_mask_deconv/Reshape)]]
	 [[Node: Mean_9/_5017 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_17513_Mean_9", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

I guess my humble 2GB GPU is not enough... how could I solve this? I do not see any batch size option implemented, is there any at all? Do you think that would that solve my issue? I would appreciate all kind of suggestions. Thanks.

**Comment by waleedka** [comment]
I'm afraid this model is fairly big so might not fit on 2GB. Here are a few things you can try:

* Smaller batch size. You control the batch size indirectly by setting GPU_COUNT and IMAGES_PER_GPU in the configuration. 
* Smaller image size. You control that in the config as well with IMAGE_MIN_DIM and IMAGE_MAX_DIM.
* Smaller network. You can use Resnet50 instead of Resnet101. See https://github.com/matterport/Mask_RCNN/issues/5

**Comment by fastlater** [comment]
The changes mentioned by @waleedka  worked for me. 
IMAGES_PER_GPU = 1
IMAGE_MIN_DIM = IMAGE_MAX_DIM = 128
_, C2, C3, C4, C5 = resnet_graph(input_image, "resnet50", stage5=True) in model.py

My mAP was about 0.67 only but at least I was able to make the script runs till end.

**Comment by RituYadav92** [comment]
Hi @waleedka I am using 32GB RAM and still facing OOM error while training on 4+ or more layers.
I have a question about the max size of images we can use because I am using comparatively larger images(1600,1600).
Could you or anyone here please clarify if there is any way to train all layers on large images with resnet101 backbone?
Thank you in advance!

**Comment by Christophe-pere** [comment]
Hi,

I had the same error and solved it with changing the number of image per GPU passing from 5 to 4. You can also configure tensorflow with tf.Session and tf.GPUOptions.

**Comment by RituYadav92** [comment]
I used 2 images per gpu which didn't work so I had to resiz images to 1024x1024 and it worked.
