### ISSUE TITLE
GPU run out of memory

### ISSUE THREAD

**Issue by chuntailin** [matterport/Mask_RCNN#587]
I am trying to train the mask rcnn mode with coco weights on my  dataset on a gtx 1080ti 8gb on Ubuntu 16.04. The images' resolutions are all 512x512. Every time I call train(), the kernel runs out of memory and crashed. I can run all the samples but except for my own dataset. The cuda version installed is 9.0, and cudnn is 7.0 now. I have tried cuda9.1 and cudnn7.1, but still cannot solve the problem. BTW, I can run successfully with CPU. Posted below is my config output.

```
Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [ 0.1  0.1  0.2  0.2]
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.5
DETECTION_NMS_THRESHOLD        0.3
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_MAX_DIM                  512
IMAGE_META_SIZE                15
IMAGE_MIN_DIM                  512
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [512 512   3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [ 123.7  116.8  103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           medical
NUM_CLASSES                    3
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [ 0.1  0.1  0.2  0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                300
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001
```

**Comment by zungam** [comment]
Not sure what taking up your memory. Could be alot of things. Using your settings, my model takes up 9GB gpu memory. Lets downsize the amount of GPU RAM used to see if it stills runs, at least.
BACKBONE  = resnet50
MAX_GT_INSTANCES = 50
POST_NMS_ROIS_INFERENCE = 500
POST_NMS_ROIS_TRAINING = 1000
RPN_TRAIN_ANCHORS_PER_IMAGE = 512

Also, try
Try CUDNN 9.0 with tf 7.1

**Comment by JingyuQian** [comment]
When the program crashes, could you try 'nvidia-smi' command in the ubuntu console? 

As @zungam mentioned it could be various reasons. With this, at least you can identify if other programs are taking up your GPU memory.

**Comment by chuntailin** [comment]
Thanks for your advices. I’m sure that there isn’t any programs are running with gpu. I solved the problem by reducing the parameters’ value just like @zungam mentioned. Finally, I found out that I can simply replace the BACKBONE “resnet101” with “resnet50” to make the program running successfully.

BTW, I also found out that everytime I running the model, the gpu would not be released even the program has finished. This situation will take place not only in my program but also in the samples such as balloon, shapes.

**Comment by liangbo-1** [comment]
@zungam@chuntailin How to replace the BACKBONE “resnet101” with “resnet50”?

**Comment by chuntailin** [comment]
@liangbo-1 BACKBONE is the attribute of Config, so you need to revise the value of BACKBONE in Config. You can see the examples in "sample" folder.

**Comment by zungam** [comment]
@chuntailin , does it stop when you fire it up, or does it stop after a while running?

**Comment by waleedka** [comment]
You're right, training all layers requires more memory. If your image domain is not drastically different from natural COCO images then you'd get pretty good results training layers "3+" or "4+" without training all layers.

I put a page summarizing the most common memory optimizations here:
https://github.com/matterport/Mask_RCNN/wiki

**Comment by chuntailin** [comment]
@waleedka  Thanks for your help. The content of the page helps me a lot. I will take these advise when I start training next time.
BTW, actually I'm training on medical images, so I think it's still need to train all layers.

**Comment by PratibhaT** [comment]
@zungam I set the the parameters same as yours...I'm trying to run the sample code of baloon with resnet50 backbone but my gpu usage goes to 10.7 GBs and since I've a gpu of 11GB it crashes. Any suggestion on how to make it run?

**Comment by chuntailin** [comment]
@PratibhaT  I'm using GTX 1080 8GB and I can successfully run the sample code of ballon with default config. So I don't think that it will crash with GPU of 11GB. Does it crash when you training first time? I found out that jupyter notebook would not release the session of tensorflow, so you have to kill the process after the training every time.

You can try "nvidia-smi" command to see whether the GPU is full of usage before you start the new training process.

**Comment by PratibhaT** [comment]
@chuntailin I tried it on another 12GB gpu and it was running fine on it. It is taking 11.785GB gpu. What changes you made to run it on 8GB? Also it is taking 4sec to evaluate 1 image, Is it that in you case too? because I need a network that can run the segmentation in real time.

**Comment by csyang6052** [comment]
@PratibhaT May I ask which 12GB gpu you adopted for making it work? Titan Xp ,or Titan V, or else? I'm facing the same memory issue when I trained my own dataset using matterport's Mask_RCNN code with one 1080ti 11GB card. Cuda and Cudnn are 9.0.176 and 7.2.1, respectively. Tensorflow-gpu==1.5.0, Python==3.6.6, and Keras==2.2.0 . I am able to complete the training work using the cpu only, though it takes a long time. I've tried zungam's and waleedka's suggestions, couldn't help so far, however.

**Comment by breazyG** [comment]
@chuntailin 
I follow your match, my program can run, really thank you very much

**Comment by akshayacharya97** [comment]
HI, I am running the default coco dataset for my own segmentation use case. I am using a jetson xavire nx with jetpack 4.5 and tensorflow 1.15.4 . It is taking forever to load the model and tensorflow is taking too long to process even a single image. I am not sure if it is even using the inbuilt gpu. The jetson has only yensorflow 1.15.5 or tensorflow 2. So im not sure if its the tensorflow version which is causing the lag. How do i go about this?

**Comment by mcmahobr** [comment]
> You're right, training all layers requires more memory. If your image domain is not drastically different from natural COCO images then you'd get pretty good results training layers "3+" or "4+" without training all layers.
> 
> I put a page summarizing the most common memory optimizations here:
> https://github.com/matterport/Mask_RCNN/wiki

Following this solved my issues. Mainly resizing images allowed me to run "all" on a Nvidia Quadro M2200 4GB GPU. 
Images were 1280 MAX DIM but I changed MAX DIM to 768 to get it running. 

Recently changed to GPU from CPU and had OOM errors forever until finding this thread. Made an account just to comment my thanks for the answers above.
